### ISSUE TITLE
ssrOnly not work with next.js

### ISSUE THREAD

**Issue by bluelovers** [hadeeb/react-lazy-hydrate#9]
![image](https://user-images.githubusercontent.com/167966/72312171-30e39d00-36c2-11ea-91b2-cbd08ce17fb3.png)

![image](https://user-images.githubusercontent.com/167966/72312202-4e186b80-36c2-11ea-9c70-d3c2320442de.png)

https://github.com/bluelovers/tpl-next-app/blob/master/components/IsServer.tsx

https://github.com/bluelovers/tpl-next-app/blob/780aee0a8bb829678707ca879d9db48ed8fd6915/pages/index.tsx#L91-L98

live demo: https://tpl-next-app.now.sh/

**Comment by hadeeb** [comment]
current logic checks for SSR content [here](https://github.com/hadeeb/react-lazy-hydration/blob/780a653629b3c221d638bed80024983fb404a49e/src/index.tsx#L50)

It's failing because your content does not have any childElements.

Try wrapping the content in an HTML element.
```diff
-       return <>
+       return <span>
                server: {String(typeof window === 'undefined')} {process.browser.toString()}
-       </>;
+       </span>;
```

demo: https://tpl-next-app-three-opal.now.sh/

**Comment by bluelovers** [comment]
thx

**Comment by bluelovers** [comment]
maybe this can make it support Fragment
https://stackoverflow.com/questions/49012718/check-if-a-child-is-react-fragment
